import os

WEBHOOK_SECRET = os.getenv("WEBHOOK_SECRET", "CHANGE_ME")
ALLOWED_TIMEFRAMES = {30}
REQUIRE_SETUP = "MMXM_4C_D"

SYMBOL_MAP = {
    "SP500": "SP500",
    "SP:SPX": "SP500",
    "OANDA:SPX500USD": "SP500",
    "FOREXCOM:SPXUSD": "SP500",
    "FX:SPX500": "SP500",
    "CAPITALCOM:US500": "SP500",
    "EURUSD": "EURUSD",
    "OANDA:EURUSD": "EURUSD",
    "FX:EURUSD": "EURUSD",
    "FOREXCOM:EURUSD": "EURUSD",
    "PEPPERSTONE:EURUSD": "EURUSD",
}
